import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const YekanBakh = localFont({
  src: '../public/font/YekanBakhFaNum-Regular.woff2',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={`bg-slate-900 text-slate-200 ${YekanBakh.className}`}>{children}</body>
    </html>
  );
}
