import "./globals.scss";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "../components/header";
import UserProvider from "./hooks/userProvider";
// import CategoryProvider from "./hooks/categoryProvider";

const YekanBakh = localFont({
  src: "../public/font/YekanBakhFaNum-Regular.woff2",
});

export const metadata: Metadata = {
  title: "AranAsayesh",
  description: "Generated by AranAsayesh",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <UserProvider>
      {/* <CategoryProvider> */}
        <html lang="fa-IR" dir="rtl">
          <body style={{marginRight: "0 !important", overflow: "auto !important"}}
            className={`w-full h-screen min-h-screen overflow-y-auto ${YekanBakh.className}`}
          >
            <header className="shadow-md border-b-1 shadow-[#00000040]">
              <Header />
            </header>
            <main className="flex min-h-screen flex-col items-center justify-between p-24">
              {children}
            </main>
          </body>
        </html>
      {/* </CategoryProvider> */}
    </UserProvider>
  );
};

export default RootLayout;
